#!/bin/bash

cd /tmp

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf cr_$1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

if [ ! -d "~/.config/rclone" ]
then
	mkdir -p ~/.config/rclone
	echo "$rclone_config" > ~/.config/rclone/rclone.conf
fi

time rclone copy cr_ccache.tar.gz gdrive:ccache/ci2 -P
